print("ingrese sus medidas")
ladoA= int(input("Lado 1"))
ladoB= int(input("Lado 2"))
Resultado= ladoA*ladoA
print("El area del cuadrado es", Resultado)
Resultado2= (ladoA*ladoB)/2
print("El area del triangulo es ", Resultado2)

input("""
         ...........
          .........
           .......
            .....
             ...
              .

        ............
        ............
        ............
        ............
        ............
        ............
        ............
        ............
""")
